# Generated by Django 5.1.2 on 2024-11-05 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('region', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('donation_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='region.region')),
            ],
        ),
    ]
