version: '3'

services:
  app:
    # image: nginx:latest
    build:
      context: .
      args:
        DEV: "TRUE"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
